spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: timefass@gmail.com
    password: eqop wpuz uzmo xlpa
    properties:
      mail: 
        smtp:
          starttls: 
            enable: true
          ssl:  
            trust: *
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
  config:
    import: "optional:configserver:"
      
server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG