spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patient-db
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    config:
      enabled: true
server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG